proxychains-ng: needs dynamic library support
Fix below build error if BR2_PREFER_STATIC_LIB is set:

src/libproxychains.c:34:19: fatal error: dlfcn.h: No such file or directory
compilation terminated.
make[1]: *** [src/libproxychains.o] Error 1

In additional, the README file also mentions that this program works only on
dynamically linked programs.

Signed-off-by: Axel Lin <axel.lin@ingics.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>