supervisor: add runtime dependency on python-setuptools
supervisor has a runtime dependency on python-setuptools which was not
expressed in its Config.in file. When running supervisor without setuptools,
one gets:

Starting supervisord: Traceback (most recent call last):
  File "/usr/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

Partially fixes bug #7184 (https://bugs.busybox.net/show_bug.cgi?id=7184)

Reported-by: Sebastian Himberger <sebastian@himberger.de>
Signed-off-by: Thomas De Schampheleire <thomas.de.schampheleire@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>